fix: fixing a bug in task controller addTask function
GSG-G13/Trakio-api pull request #109
Opened 2023-06-18 13:54 UTC by KhaledToha

2023-06-18 13:58 UTC, Mohammed-Sbeata approved these changes
PRAAAAVOOOO

2023-06-18 22:51 UTC, nada-abuzaid requested changes

2023-06-18 22:51 UTC, nada-abuzaid commented on src/controllers/task.ts
> +      if (data.rows.length === 0) {
```suggestion
      if (!data.rows.length) {
```

2023-06-18 22:51 UTC, nada-abuzaid commented on src/controllers/task.ts
>    const projectId = Number(req.params.id);
what about validation here? if the req.params.id = "3N" for example?

2023-06-18 22:52 UTC, nada-abuzaid requested changes

2023-06-18 22:52 UTC, nada-abuzaid commented on src/controllers/task.ts
> +    .then(() => checkForMemberInProject(userId, projectId))
```suggestion
    .then(() => checkForMemberInProject({userId, projectId}))

```

2023-06-19 07:13 UTC, nada-abuzaid approved these changes
شكرا يا خالد

2023-06-19 07:14 UTC, merged