Create file structure
GSG-G13/Trakio-api pull request #3
Opened 2023-06-09 13:07 UTC by Amal-Mousa

2023-06-09 13:27 UTC, KhaledToha requested changes

2023-06-09 13:27 UTC, KhaledToha commented on app.ts
you should define app, req, and res based on their types.
first, you need to get their types from express module like this:

const {Express, Request, Response} = require('express')

then you can declare them:
const app: Express = express()

app.get('/', (req: Request, res: Response) =>{})

**It's a bad practice to declare any variable with type of any**

2023-06-10 08:41 UTC, nada-abuzaid requested changes

2023-06-10 13:42 UTC, KhaledToha approved these changes

2023-06-10 14:26 UTC, nada-abuzaid approved these changes

2023-06-10 14:27 UTC, merged