fix: fixing a promise bug in signUp controller
GSG-G13/Trakio-api pull request #40
Opened 2023-06-12 19:23 UTC by KhaledToha

2023-06-12 19:37 UTC, AyaAljalees approved these changes
نردلك اياها بالافراح

2023-06-12 19:45 UTC, nada-abuzaid approved these changes

2023-06-12 19:48 UTC, Mohammed-Sbeata approved these changes

2023-06-13 07:06 UTC, nada-abuzaid requested changes

2023-06-13 07:06 UTC, nada-abuzaid commented on src/controllers/auth.ts
> +import { TokenRequest, joiInterface, userData } from '../interfaces';
where is the joiInterface?

2023-06-13 07:06 UTC, nada-abuzaid commented on src/controllers/auth.ts
> +// const hashPassword = (userPassword: string): Promise<string> => bcrypt.hash(userPassword, 10);
remove any commented code

2023-06-13 08:59 UTC, nada-abuzaid approved these changes

2023-06-13 09:00 UTC, merged