Create delete task by task_id controller
GSG-G13/Trakio-api pull request #54
Opened 2023-06-13 11:08 UTC by Mohammed-Sbeata

2023-06-13 11:57 UTC, AyaAljalees approved these changes

2023-06-13 16:30 UTC, KhaledToha approved these changes
Good job

2023-06-13 17:00 UTC, nada-abuzaid requested changes

2023-06-13 17:00 UTC, nada-abuzaid commented on src/routers/task.ts
> +taskRouter.delete('/task/delete', authCheck, deleteTaskById)
```suggestion
taskRouter.delete('/task', authCheck, deleteTaskById)

```

2023-06-13 17:00 UTC, nada-abuzaid commented on src/controllers/task.ts
> +  const { taskId } = req.params;
you get the taskId from the param, how you can access the params here? have you tried to print it?

2023-06-13 17:00 UTC, nada-abuzaid commented on src/controllers/task.ts
> +      res.status(204).json({
204 status means that is no content returned, so we don't have any response here.

A [204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) (No Content) status code if the action has been enacted and no further information is to be supplied.
A [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) (OK) status code if the action has been enacted and the response message includes a representation describing the status.

 read more [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE)

2023-06-14 08:00 UTC, nada-abuzaid approved these changes

2023-06-14 08:00 UTC, merged