Add get user task controller
GSG-G13/Trakio-api pull request #56
Opened 2023-06-13 12:59 UTC by AyaAljalees

2023-06-13 13:46 UTC, Amal-Mousa approved these changes

2023-06-13 17:29 UTC, nada-abuzaid requested changes

2023-06-13 17:29 UTC, nada-abuzaid commented on src/controllers/tasks.ts
> +      throw new CustomError(500, 'Server Error');
throw error from the catch to where? use `next` here to send the error to the serverError middleware
"we use throw error in the `then` section `ya 3asal`"

2023-06-13 17:29 UTC, nada-abuzaid commented on src/controllers/tasks.ts
> +        data: tasks,
we need to return the rows array here, not all the query result

```suggestion
        data: tasks.rows,
```

2023-06-13 17:29 UTC, nada-abuzaid commented on src/controllers/tasks.ts
> +import { getTasksByUserId } from '../database/query/tasks';
import it from the index file 

```suggestion
import { getTasksByUserId } from '../database/query';
```

2023-06-14 07:30 UTC, Mohammed-Sbeata approved these changes

2023-06-14 07:31 UTC, KhaledToha approved these changes

2023-06-14 07:31 UTC, merged