Create get attachment query
GSG-G13/Trakio-api pull request #74
Opened 2023-06-14 16:01 UTC by Mohammed-Sbeata

2023-06-14 20:09 UTC, KhaledToha requested changes

2023-06-14 20:09 UTC, KhaledToha commented on src/database/query/attachment.ts
we need to get the attachments by task id no need to use the user id

2023-06-15 06:54 UTC, AyaAljalees approved these changes

2023-06-15 07:41 UTC, Amal-Mousa approved these changes

2023-06-15 07:42 UTC, nada-abuzaid approved these changes

2023-06-15 07:43 UTC, merged