Create add attachments query
GSG-G13/Trakio-api pull request #78
Opened 2023-06-14 17:42 UTC by Mohammed-Sbeata

2023-06-14 20:28 UTC, KhaledToha approved these changes

2023-06-15 03:13 UTC, nada-abuzaid requested changes

2023-06-15 03:13 UTC, nada-abuzaid commented on src/database/query/attachment.ts
> +};
```suggestion

```

2023-06-15 06:36 UTC, nada-abuzaid approved these changes

2023-06-15 06:50 UTC, Amal-Mousa approved these changes

2023-06-15 06:53 UTC, merged