refactor: move validation folder
GSG-G13/Trakio-api pull request #88
Opened 2023-06-15 09:58 UTC by AyaAljalees

2023-06-15 09:59 UTC, Amal-Mousa approved these changes

2023-06-15 13:12 UTC, KhaledToha approved these changes

2023-06-17 12:20 UTC, Mohammed-Sbeata approved these changes
Good Job 👏

2023-06-17 12:43 UTC, KhaledToha requested changes

2023-06-17 12:43 UTC, KhaledToha commented on src/controllers/auth.ts
> +    .catch((error)=>next(error));
we should determine if the error came from validation or else
so make it like this 
.catch((err: CustomError | joiInterface) => {
      if ('isJoi' in err) {
        next(new CustomError(406, err.details[0].message));
      } else {
        next(err);
      }
    });

2023-06-17 12:43 UTC, KhaledToha commented on src/controllers/auth.ts
> -    });
same as signupController

2023-06-17 12:45 UTC, Amal-Mousa commented on src/controllers/auth.ts
> -    });
ok ع راسي

2023-06-17 13:53 UTC, KhaledToha approved these changes

2023-06-17 14:16 UTC, nada-abuzaid approved these changes

2023-06-17 14:17 UTC, merged